name = "CausalityToolsBase"
uuid = "b1f25513-c649-51ee-8a1c-0e98d01ae897"
authors = ["Kristian Agasøster Haaga <kahaaga@gmail.com>"]
repo = "https://github.com/kahaaga/CausalityToolsBase.jl"

[deps]
DelayEmbeddings = "5732040d-69e3-5649-938a-b6b4f237613f"
